config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'menu' => 'pages#menu'
  namespace :stripe do
    resources :checkouts
    post 'webhook' => 'checkouts#webhook'
    post 'add' => 'checkouts#new'
    get 'cart' => 'checkouts#show'
    get 'finalize' => 'checkouts#create'
    get 'thanks' => 'checkouts#thanks'
    get 'restart' => 'checkouts#destroy'
  end
  resources :subscriptions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chip.rb
class Chip < ApplicationRecord
    
  belongs_to :menu
    
end

app/models/concerns/stripe_tool.rb
module StripeTool
  def self.create_customer(email: :email)
    Stripe::Customer.create(
      email: email
    )
  end

  def self.create_charge(customer_id: :customer_id, amount: :amount, description: :description)
    Stripe::Charge.create(
      customer: customer_id,
      amount: amount,
      description: description,
      currency: 'usd'
    )
  end
    
  def self.create_membership(email: :email, stripe_token: :stripe_token, plan: :plan)
    Stripe::Customer.create(
      email: email,
      source: stripe_token,
      plan: plan
    )
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
    
  has_many :chips
    
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    
  belongs_to :user
    
  def interrupt
    Stripe::Subscription.delete(stripe_id)
    self.active = false
    save
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  
  has_one :subscription
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @chips = Chip.all
    @user = current_user
  end
    
  def menu
    @og = Chip.find_by_id(id=1)
    @new = Chip.find_by_id(id=2)
  end

  def about
  end

end

app/controllers/stripe/checkouts_controller.rb
class Stripe::CheckoutsController < ApplicationController
  before_action :get_cart_total
  before_action :authenticate_user!
  
  def new
    add_cookie_to_cart(params) if params
    flash[:success] = "Cart updated"
    redirect_to root_path
  end

  def show
  end

  def create
    if current_user.stripe_id?
      customer = Stripe::Customer.retrieve(current_user.stripe_id)
    else
      customer = StripeTool.create_customer(
        email: current_user.email
      )
    end
    
    current_user.update!(stripe_id: customer.id)
    stripe_session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      line_items: session[:line_items],
      customer: customer.id,
      client_reference_id: current_user.id,
      mode: 'payment',
      success_url: "#{stripe_thanks_url}?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: root_url
    })
      
    redirect_to stripe_session.url
  rescue Stripe::InvalidRequestError => e
    flash[:error] = 'You silly goose! Your cart is empty!'
    redirect_to stripe_cart_path
  end
 
  def thanks
    session.delete(:line_items)
    flash[:success] = "Purchase successful"
  end

  def destroy
    session.delete(:line_items)
    flash[:success] = "Cart deleted"
    redirect_to stripe_cart_path
  end

  def webhook
    sig_header = request.env['HTTP_STRIPE_SIGNATURE']

    begin
      event = Stripe::Webhook.construct_event(request.body.read, sig_header, ENV['STRIPE_ENDPOINT_SECRET'])
    rescue JSON::ParserError
      return head :bad_request
    rescue Stripe::SignatureVerificationError
      return head :bad_request
    end

    webhook_checkout_session_completed(event) if event['type'] == 'checkout.session.completed'

    head :ok
  end

  def interrupt
    current_user.subscription.interrupt
  end
    
  
  private
    
  def add_cookie_to_cart(params)
    price = params[:item][:menu_id].to_i == 1 ? 150 : 200
    line_item = {
      price_data: {
        unit_amount: price,
        currency: 'usd',
        product_data: {
          name: params[:item][:name],
          images: [params[:item][:image]]
        },
      },
      quantity: params[:item][:quantity]
    }
    session[:line_items].push(line_item)
  end

  def get_cart_total
    @amount = 0
    if session[:line_items]
      session[:line_items].each do |i|
        quantity = i['quantity'].to_i
        price = i['price_data']['unit_amount'].to_i
        @amount += price * quantity
      end
    else
      session[:line_items] = Array.new
    end
  end

  def build_subscription(stripe_subscription)
    Subscription.new(plan_id: stripe_subscription.plan.id,
                     stripe_id: stripe_subscription.id,
                     current_period_ends_at: Time.zone.at(stripe_subscription.current_period_end))
  end

  def webhook_checkout_session_completed(event)
    object = event['data']['object']
    customer = Stripe::Customer.retrieve(object['customer'])
    #stripe_subscription = Stripe::Subscription.retrieve(object['subscription'])
    #subscription = build_subscription(stripe_subscription)
    user = User.find_by(id: object['client_reference_id'])
    #user.subscription.interrupt if user.subscription.present?
    user.update!(stripe_id: customer.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents / 100)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Cookies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'menu', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="content">

        <%= link_to root_path, class: "desktop" do %>
          <%= image_tag "logo-background.svg", id: "background", class: "icon" %>
          <h1>cookies</h1>
          <%= image_tag "logo-name.svg", id: "name", class: "icon" %>
        <% end %>

        <nav class="desktop">
          <ul>
            <%- if current_user %>
            <li class="session-user">
              <%= link_to "LOGOUT", destroy_session_path(current_user), method: :delete, class: "logout" %>
              <p><%= current_user.email %><p>
            </li>
            <% end %>
            <li><%= link_to "MENU", menu_path %></li>
            <li><%= link_to "ABOUT", about_path %></li>
            <li><%= link_to "CART", stripe_cart_path %></li>
            <li>
              <%= link_to "https://www.instagram.com/cookiesbyrelle/" do %>
                <%= image_tag "heart-solid.svg", id: "heart", class: "icon" %>
              <% end %>
            </li>
          </ul>
        </nav>

        <nav class="mobile">
          <ul>
            <li class="head-status">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
            </li>
            <li>
              <%- if current_user %>
              <%= link_to destroy_session_path(current_user), method: :delete, class: "logout" do %>
                <%= image_tag "logout.svg", id: "logout", class: "icon logout" %>
              <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://www.instagram.com/cookiesbyrelle/" do %>
                <%= image_tag "heart-solid.svg", id: "heart", class: "icon" %>
              <% end %>
            </li>
            <div class="dropdown">
              <li>
                <a>
                  <%= image_tag "bars-solid.svg", id: "bars", class: "icon dropbtn" %>
                </a>
              </li>
              <div class="dropdown-content">
                <li><%= link_to "MENU", menu_path %></li>
                <li><%= link_to "ABOUT", about_path %></li>
                <li><%= link_to "CART", stripe_cart_path %></li>
              </div>
            </div>
          </ul>
        </nav>

      </div>
    </header>

    <%= yield %>

    <div id="spacing" class="container">
    </div>

    <footer>
      <div class="content">
        <span class="copyright">&copy; 2021 Cookies by Relle</span><a href="https://the-tacderan-code.herokuapp.com"><strong>BRIAN TACDERAN</strong></a>
        <nav class="desktop">
          <ul>
            <li><a href="#">Terms</a></li>
            <li><a href="#">Privacy</a></li>
          </ul>
        </nav>
      </div>
    </footer>

    <script src="//cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.sidr/2.2.1/jquery.sidr.min.js"></script>

  </body>
</html>

app/views/pages/home.html.erb
<div id="main-content">
  <div id="banner-section">
    <div id="banner">
      <div class="space" id="first"></div>
      <div id="banner-left" class="container">
        <%= image_tag "cookie_3.jpg", class: "desktop" %>
        <%= image_tag "misc-choc.png", id: "parallaxOne", class: "mobile" %>
      </div>
      <div class="space"></div>
    </div>
    <div id="banner-right">
      <div class="container">
        <div class="content">
          <h1>fresh cookies</h1>
          <h3>MADE TO ORDER</h3>
          <p>every cookie baked with <strong>hella love</strong></p>
          <%= link_to "MENU LIST", menu_path, id: "banner-button", class: "button" %>
        </div>
      </div>
    </div>
  </div>

  <div id="bulletin-section">
    <div id="bulletin-container">
      <div id="bulletin-left" class="bulletin-half" style="background: url(<%= image_url 'white-stripes.svg' %>); background-color: #f1f1f1;">

        <div id="post-title">
          <div id="post-title-container" class="container">
            <h1>COOKIE MENU</h1>
          </div>
        </div>

        <div id="post-container">
          <%- if flash[:success].present? %>
          <div id="success-update" class="post">
            <p><%= flash[:success] %></p>
          </div>
          <% end %>
          <% @chips.each_with_index do |chip, index| %>
          <div id="post-<%= index+1 %>" class="post">
            <div class="content">
              <%= form_for(:item, :url => stripe_add_path) do |f| %>
                <div class="field hidden-field">
                  <%= f.hidden_field :name, value: chip.name %>
                </div>
                <div class="field hidden-field">
                  <%= f.hidden_field :menu_id, value: chip.menu_id %>
                </div>
                <div class="field hidden-field">
                  <%= f.hidden_field :image, value: chip.image %>
                </div>
                <h4><%= chip.name %></h4>
                <p><%= chip.description %></p>
                <div class="quantity-submit">
                  <div id="quantity-counter-<%= index+1 %>" class="field quantity-counter">
                    <%= f.label :quantity, "QUANTITY" %>
                    <%= f.number_field :quantity, in: 1..12, step: 1, autocomplete: 1 %>
                  </div>
                  <div id="submit-<%= index+1 %>" class="actions">
                    <%= f.submit "ADD TO CART" %>
                  </div>
                </div>

              <% end %>
            </div>
          </div>
          <% end %>
        </div>

      </div>

      <div id="bulletin-right">
        <div class="parallax">
          <%= image_tag "cookie_3.jpg", id: "parallaxTwo", class: "bull-right" %>
          <%= image_tag "pink-chip.png", id: "parallaxThree", class: "bull-right" %>
        </div>
      </div>
    </div>
  </div>

  <div id="newsletter-section">
    <div class="container" style="background-image: url(<%= image_url 'white-stripes.svg' %>);">
      <div class="content">
        <h1>subscribe to the <strong>cookies</strong> club</h1>
        <span>Get on our member list and never miss out on new flavors and promotions or click on the <strong>HEART</strong>at the top of the page and follow us on @instagram</span>
      </div>
      <div id="subscribe">
        <form>
          <input type="text"
                 class="form-control"
                 placeholder="Email address"
                 aria-label="Email address" />
          <span>
            <button type="button">SUBSCRIBE</button>
          </span>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/pages/menu.html.erb
<div id="menu-section" style="background-image: url(<%= image_url 'white-stripes.svg' %>); background-color: black;">
  <div id="cookie-category">
    <div id="category-background">
      <div class="space" id="first"></div>
      <div id="original" class="cat-name">
        <h1 class="cat-name">original recipes</h1>
        <%= image_tag "same-chips.png", id: "cat-one", class: "original" %>
      </div>
      <div id="seasonal" class="cat-name">
        <h1 class="cat-name">new &amp; seasonal</h1>
        <%= image_tag "misc-chips.png", id: "cat-two", class: "seasonal" %>
      </div>
      <div id="bulletin-section">
        <div id="bulletin-container">
          <div id="bulletin-left" class="bulletin-half" style="background: url(<%= image_url 'white-stripes.svg' %>); background-color: #f1f1f1;">

            <div id="post-title">
              <div id="post-title-container"
                   class="container">
                <h1>COOKIE MENU</h1>
              </div>
            </div>

            <div id="post-container">
              <%- if flash[:success].present? %>
              <div id="success-update" class="post">
                <p><%= flash[:success] %></p>
              </div>
              <% end %>

              <

              <% @chips.each_with_index do |chip, index| %>
              <div id="post-<%= index+1 %>" class="post">
                <div class="content">
                  <%= form_for(:item, :url => stripe_add_path) do |f| %>
                    <div class="field hidden-field">
                      <%= f.hidden_field :name, value: chip.name %>
                    </div>
                    <div class="field hidden-field">
                      <%= f.hidden_field :menu_id, value: chip.menu_id %>
                    </div>
                    <div class="field hidden-field">
                      <%= f.hidden_field :image, value: chip.image %>
                    </div>
                    <h4><%= chip.name %></h4>
                    <p><%= chip.description %></p>
                    <div class="quantity-submit">
                      <div id="quantity-counter-<%= index+1 %>" class="field quantity-counter">
                        <%= f.label :quantity, "QUANTITY" %>
                        <%= f.number_field :quantity, in: 1..12, step: 1, autocomplete: 1 %>
                      </div>
                      <div id="submit-<%= index+1 %>" class="actions">
                        <%= f.submit "ADD TO CART" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'menu' %>

app/views/stripe/checkouts/destroy.html.erb
<%= stylesheet_link_tag 'stripe', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/stripe/checkouts/new.html.erb
<%= stylesheet_link_tag 'stripe', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/stripe/checkouts/show.html.erb
<%= stylesheet_link_tag 'stripe', media: 'all', 'data-turbolinks-track': 'reload' %>

<div id="cart-view-section" class="checkouts-page">
  <div id="cart-view-container" class="checkouts-container">

    <article>
      <%- if flash[:error].present? %>
      <div id="error-explanation">
        <p><%= flash[:error] %></p>
      </div>
      <% end %>
    </article>

    <div id="cart-view-content" class="checkouts-content">
      <div id="cart-view">

        <div id="cart-details">
          <label class="amount">
            <div id="cart-view-title" class="checkouts-page-title">
              <h1>Cart total</h1>
              <h2>
                <%= pretty_amount(@amount) unless @amount.nil? %>
                <%= "Your cart is empty" if @amount.nil? %>
              </h2>
            </div>
          </label>
        </div>

        <form id="cart-actions" class="actions">
          <%= link_to "Checkout", stripe_finalize_path %>
          <%= link_to "Delete all items", stripe_restart_path %>
        </form>
          
      </div>
    </div>

  </div>
</div>

app/views/stripe/checkouts/thanks.html.erb
<%= stylesheet_link_tag 'stripe', media: 'all', 'data-turbolinks-track': 'reload' %>

<div id="cart-view-section" class="checkouts-page">
  <div id="cart-view-container" class="checkouts-container">

    <article>
      <%- if flash[:error].present? %>
      <div id="error-explanation">
        <p><%= flash[:error] %></p>
      </div>
      <% end %>
    </article>

    <div id="cart-view-content" class="checkouts-content">
      <div id="cart-view">
        <div id="cart-details">
          <label class="amount">
            <div id="cart-view-title" class="checkouts-page-title">
              <h1>Purchase successful</h1>
              <h2>You were successfully charged for your cookie order!</h2>
            </div>
          </label>
        </div>

        <form id="cart-actions" class="actions">
          <%= link_to "LOGOUT", destroy_session_path(current_user), method: :delete, class: "logout" %>
          <%= link_to "GO BACK TO MENU", menu_path %>
        </form>
      </div>
    </div>
  </div>
</div>